apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Gitauwairimu/GitOps--ghjavamvn.git
    targetRevision: HEAD
    path: overlays
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    refresh:
      interval: 5m

  overlays:
  - dev
  - staging
  - prod

  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
