apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: CircleCi  #Slack Channel name
    
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/gitauwairimu/javamvn:5610880369     #Write repository name
    # argocd-image-updater.argoproj.io/myalias.pull-secret: pullsecret:argocd/argocd-docker-secret  # You can remove this annotation if you have already configured the gcr secret and are using the same secret to retrieve all GCR images in your deployments.
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest #There are several ways to update the image, but I'm using digest.
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds  # We don't need the secret as mentioned in argocd doc because we already set it up via argocd console if you're using the same git repo.
    argocd-image-updater.argoproj.io/git-branch: main 
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
    # argocd-image-updater.argoproj.io/source-type: Kustomize
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    # argocd-image-updater.argoproj.io/myalias.allow-tags: regexp:^[0-9]+
spec:
  project: default

  source:
    repoURL: https://github.com/Gitauwairimu/GitOps--ghjavamvn.git
    targetRevision: HEAD
    path: dev
    # path: overlays/dev, overlays/staging, overlays/prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true
  #   refresh:
  #     interval: 2m

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

  # overlays:
  # - dev
  # - staging
  # - prod
