apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: javamvn
  name: javamvn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javamvn
  template:
    metadata:
      labels:
        app: javamvn
    spec:
      containers:
      - image: gitauwairimu/javamvn:5148240302
        name: javamvn
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

status:
  replicas: 2
  readyReplicas: 2
  availableReplicas: 2
